services:
  - type: web
    name: mental-health-backend
    env: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://hdeng24:kSzsv6GMmllSJiud@cluster0.uflqh.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: anytext
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production

  - type: static
    name: mental-health-frontend
    env: static
    rootDir: Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        sync: false